package fi.hiit.jexpeng.event;


public enum EventType {
    EXPERIMENT_START, EXPERIMENT_END,
    CHOOSE_NEXT_TASK, TASK_START, TASK_END,
    CHOOSE_NEXT_GROUP, TASK_GROUP_START, TASK_GROUP_END,
    ITERATION_START, ITERATION_END,
}
